permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: CICEL-PRG
  email: scyaprg@gmail.com
  github: http://github.com/cicelprg

# 站点信息
title: CICEL-PRG
description: I am coder?

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico


# disqus 设置
disqus:
  shortname: prg-zh

# 主题设置，自动激活某个标签
active: CODER

# 首页除了最新文章外显示分类
cates: 
  - PHP
  - MYSQL

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
